FROM node:16-alpine

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci

# Копирование проекта
COPY . ./

# Порт для React dev сервера
EXPOSE 3000

# Запуск dev сервера
CMD ["npm", "start"] 